management:
  security:
    enabled: false
    #prometheus+grafana+springboot2监控集成配置
  metrics:
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      #prometheus+grafana+springboot2监控集成配置
server:
  port: 13110

sentinel-plus-dashboard:
  dashboard-service-manager:
    fetch-metric-interval-seconds: 6

spring:
  application:
    name: sentinel-io.github.rd.sentinel.dashboard
  datasource:
    url: jdbc:mysql://localhost:3306/sentinel?useAffectedRows=true
    username: root
    password: root
  influx:
    url: http://127.0.0.1:8086
    user: admin
    password: admin
    database: sentinel
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
